In [1]:
import pynbody
import pandas as pd

In [2]:
def loadSimulation(path: str, family=None) -> pynbody.snapshot.SimSnap:

    if family is None:
        sim = pynbody.load(path)
        sim = getattr(sim, str(sim.families()[0]))

    else:
        sim = getattr(pynbody.load(path), family)

    return sim

In [3]:
def pynbody_to_dataframe(sim, config):

    sim.physical_units()

    keys = ["x", "y", "z"]

    for key, value in config.items():
        if value:
            keys = keys + [key]

    data = {}

    for key in keys:
        if sim[key].ndim > 1:
            for i in range(sim["vel"].shape[1]):
                data[f"{key}_{i}"] = sim[key][:, i].astype(float)
            
        else:
            data[key] = sim[key].astype(float)

    df = pd.DataFrame(data)

    del sim

    return df

In [4]:
path = "/home/dev/development/data-experiments/.data/illustris_data/342447_gas.hdf5"

In [5]:
sim = loadSimulation(path)

/home/dev/development/data-experiments/.venv/lib/python3.12/site-packages/pynbody/snapshot/tipsy.py:126: RuntimeWarning: No readable param file in the run directory or parent directory: using defaults.
  warnings.warn(

In [6]:
sim.all_keys()

['HII',
 'HeIII',
 'ne',
 'hetot',
 'hydrogen',
 'feh',
 'oxh',
 'ofe',
 'mgfe',
 'nefe',
 'sife',
 'c_s',
 'c_s_turb',
 'mjeans',
 'mjeans_turb',
 'ljeans',
 'ljeans_turb',
 'U_mag',
 'U_lum_den',
 'B_mag',
 'B_lum_den',
 'V_mag',
 'V_lum_den',
 'R_mag',
 'R_lum_den',
 'I_mag',
 'I_lum_den',
 'J_mag',
 'J_lum_den',
 'H_mag',
 'H_lum_den',
 'K_mag',
 'K_lum_den',
 'u_mag',
 'u_lum_den',
 'g_mag',
 'g_lum_den',
 'r_mag',
 'r_lum_den',
 'i_mag',
 'i_lum_den',
 'z_mag',
 'z_lum_den',
 'y_mag',
 'y_lum_den',
 'r',
 'rxy',
 'vr',
 'v2',
 'vt',
 'ke',
 'te',
 'j',
 'j2',
 'jz',
 'vrxy',
 'vcxy',
 'vphi',
 'vtheta',
 'v_mean',
 'v_disp',
 'v_curl',
 'vorticity',
 'v_div',
 'age',
 'theta',
 'alt',
 'az',
 'cs',
 'mu',
 'p',
 'u',
 'temp',
 'zeldovich_offset',
 'aform',
 'tform',
 'iord_argsort',
 'smooth',
 'rho',
 'mass',
 'pos',
 'rho',
 'eps',
 'metals',
 'vel',
 'temp',
 'phi']

In [7]:
config = {
    "x": {"selected": True},
    "y": {"selected": True},
    "z": {"selected": True},
    "vel": {"selected": True},
}

In [8]:
pynbody_to_dataframe(sim, config)

,x,y,z,vel_0,vel_1,vel_2
0,25210.751953,6016.833984,33916.175781,-37101.321884,16185.092188,27565.760781
1,25217.525391,6021.164551,33916.390625,-25801.273048,20455.303290,28064.969429
2,25209.966797,6013.332520,33916.195312,-39256.316954,15397.405218,20899.627277
3,25209.419922,6013.964844,33916.269531,-26396.135875,16135.506441,23169.636786
4,25210.277344,6013.417480,33916.253906,-38408.079331,14068.404674,23005.832465
...,...,...,...,...,...,...
5337692,24997.021484,5971.073242,34181.152344,995.542666,19240.829856,-10466.078251
5337693,25128.960938,5930.252930,34424.832031,-27574.804852,13134.802164,-22734.005613
5337694,25133.708984,5983.444824,34215.996094,-21793.139049,3302.005844,-18208.785263
5337695,25251.812500,6077.382324,34277.750000,-20691.544034,-2755.496399,-7302.302228
5337696,24892.605469,5714.530273,34238.500000,-20207.971059,4216.774584,9398.739473